In [ ]:
# 전처리한 데이터프레임을 mysql에 저장

In [1]:
from sqlalchemy import create_engine
import pymysql
import pandas as pd

In [ ]:
# 식당데이터

In [2]:
RESTAURANT = pd.read_csv('RESTAURANT_FINAL.csv', index_col=0)

In [3]:
RESTAURANT = RESTAURANT.iloc[:,2:-1]

In [4]:
RESTAURANT

,name,category,locCity,locDistrict,locDetail,tel,longitude,latitude,imgUrl,summary
0,보광호,생선회,인천광역시,강화군,길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...
1,장어마을,"장어,먹장어요리",인천광역시,강화군,길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...
2,충남서산집,게요리,인천광역시,강화군,내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN
3,한옥카페 궁,"카페,디저트",인천광역시,강화군,내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛..."
4,1박2일 족발,"족발,보쌈",인천광역시,강화군,강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
18981,힘내소,"육류,고기요리",인천광역시,서구,새오개로 37,032-582-4497,126.665077,37.513626,https://search.pstatic.net/common/?autoRotate=...,NaN
18982,힘센장어,"장어,먹장어요리",인천광역시,서구,승학로236번길 20-1,032-566-1032,126.674852,37.543248,https://search.pstatic.net/common/?autoRotate=...,NaN
18983,힘찬장어 청라점,"장어,먹장어요리",인천광역시,서구,중봉대로 800,032-564-9533,126.650731,37.551228,https://search.pstatic.net/common/?autoRotate=...,국내산 일등급 풍천민물장어 즉석숯불화로구이 전문점으로서\n맛있는장어를 산지직송으로 ...
18984,힛트꼬치,"일식튀김,꼬치",인천광역시,서구,원창로240번길 3,032-579-8713,126.676069,37.517143,https://search.pstatic.net/common/?autoRotate=...,NaN
18985,쑝쑝돈까스 인천가좌점,돈가스,인천광역시,서구,장고개로 277-1,032-572-3300,126.682557,37.488767,https://search.pstatic.net/common/?autoRotate=...,바른생각을 가진 사람들이 만드는 요리 신선한 재료와 성실한 조리로 요리를 대접합니다...

In [ ]:
# db 연결

In [5]:
host = 'yh-db.cdtkthbhsama.ap-northeast-2.rds.amazonaws.com'
user = 'Eatopia_DB_user'
password = 'dltxhvldk1234db'  # db 비밀번호
db_name = 'Eatopia_DB'

In [6]:
db_connection_str = f'mysql+pymysql://{user}:{password}@{host}/{db_name}'

In [7]:
connection = create_engine(db_connection_str)

In [8]:
connection

Engine(mysql+pymysql://Eatopia_DB_user:***@yh-db.cdtkthbhsama.ap-northeast-2.rds.amazonaws.com/Eatopia_DB)

In [ ]:
# db의 restaurant 테이블에 저장

In [9]:
RESTAURANT.to_sql(name='restaurant', con=connection, if_exists='append',index=False)

18986

In [ ]:
# 메뉴데이터

In [16]:
MENU = pd.read_csv('MENU_FINAL2.csv', index_col=0)

In [17]:
MENU

,id,old_restaurantId,restaurantId,menuName,price,description,imgUrl
0,1,2,1,A세트인기대표,59000,해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,2,2,1,숭어,25000,NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
2,3,2,1,광어,40000,NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
3,4,2,1,우럭,40000,NaN,https://ldb-phinf.pstatic.net/20220207_115/164...
4,5,2,1,도미,50000,NaN,NaN
...,...,...,...,...,...,...,...
162204,162205,31201,18984,국수(잔치/열무/물냉면),4000,NaN,NaN
162205,162206,31206,18986,프리미엄카츠,7500,"프리미엄소스와 히말라야 핑크소금, 와사비마요, 생와사비를 기호에 맞게 드실 수 있는 메뉴",https://search.pstatic.net/common/?autoRotate=...
162206,162207,31206,18986,큐브치즈카츠1,8500,모짜렐라 100% 치즈가 쭈~~욱 속이 꽉찬 치즈카츠와 감자튀김을 동시에 즐기실 수...,https://search.pstatic.net/common/?autoRotate=...
162207,162208,31206,18986,큐브치즈카츠2,9500,모짜렐라 100% 치즈가 쭈~~욱 속이 꽉찬 치즈카츠와 등심돈까스를 동시에 즐기실 ...,https://search.pstatic.net/common/?autoRotate=...
162208,162209,31206,18986,모둠카츠,9500,"등심돈까스와 큐브치즈카츠, 새우튀김, 감자튀김까지 맛보실 수 있는 푸짐한 메뉴",https://search.pstatic.net/common/?autoRotate=...

In [18]:
MENU = MENU.iloc[:, 2:]

In [19]:
MENU

,restaurantId,menuName,price,description,imgUrl
0,1,A세트인기대표,59000,해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,1,숭어,25000,NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
2,1,광어,40000,NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
3,1,우럭,40000,NaN,https://ldb-phinf.pstatic.net/20220207_115/164...
4,1,도미,50000,NaN,NaN
...,...,...,...,...,...
162204,18984,국수(잔치/열무/물냉면),4000,NaN,NaN
162205,18986,프리미엄카츠,7500,"프리미엄소스와 히말라야 핑크소금, 와사비마요, 생와사비를 기호에 맞게 드실 수 있는 메뉴",https://search.pstatic.net/common/?autoRotate=...
162206,18986,큐브치즈카츠1,8500,모짜렐라 100% 치즈가 쭈~~욱 속이 꽉찬 치즈카츠와 감자튀김을 동시에 즐기실 수...,https://search.pstatic.net/common/?autoRotate=...
162207,18986,큐브치즈카츠2,9500,모짜렐라 100% 치즈가 쭈~~욱 속이 꽉찬 치즈카츠와 등심돈까스를 동시에 즐기실 ...,https://search.pstatic.net/common/?autoRotate=...
162208,18986,모둠카츠,9500,"등심돈까스와 큐브치즈카츠, 새우튀김, 감자튀김까지 맛보실 수 있는 푸짐한 메뉴",https://search.pstatic.net/common/?autoRotate=...

In [20]:
MENU.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 162209 entries, 0 to 162208
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   restaurantId  162209 non-null  int64
 1   menuName      162209 non-null  object
 2   price         162209 non-null  int64
 3   description   64255 non-null   object
 4   imgUrl        89067 non-null   object
dtypes: int64(2), object(3)
memory usage: 7.4+ MB

In [22]:
MENU['price'].value_counts()

-1         7186
 8000      6153
 10000     5714
 7000      5597
 6000      5480
           ...
 45800        1
 61800        1
 56800        1
 149900       1
 349000       1
Name: price, Length: 615, dtype: int64

In [ ]:
# db의 menu 테이블에 저장

In [23]:
MENU.to_sql(name='menu', con=connection, if_exists='append', index=False)

162209

In [ ]:
# db 연결 해제

In [24]:
connection.dispose()