In [1]:
import pandas as pd
import numpy as np

In [ ]:
# 식당 데이터 전처리

In [2]:
df1 = pd.read_csv('DF_restaurant.csv', index_col=0)

In [3]:
df1

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId
0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,1.656160e+07
2,3.0,섬고기,정육점,인천광역시 강화군 길상면 삼랑성길 4,010-3355-1796,126.491346,37.639160,https://search.pstatic.net/common/?autoRotate=...,1969년 시작된 섬고기는 \n청정지역 강화도에서 자란 질좋은 한우암소를 Wet A...,1.051601e+09
3,4.0,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,1.186197e+07
4,5.0,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,3.723998e+07
...,...,...,...,...,...,...,...,...,...,...
9995,19996.0,라네이즈PC방,PC방,인천광역시 부평구 동수북로 156,NaN,126.723541,37.488818,https://search.pstatic.net/common/?autoRotate=...,NaN,1.168486e+09
9996,19997.0,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,3.131620e+07
9997,19998.0,라마다푸드,한식,인천광역시 부평구 충선로 3-5,NaN,126.730484,37.491741,NaN,NaN,1.272767e+09
9998,19999.0,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1.577549e+09
9999,20000.0,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1.050960e+09

In [ ]:
# 전화번호 없는 경우 제거

In [4]:
df1 = df1.dropna(subset=['tel'], axis=0)

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15230 entries, 1 to 9999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           15230 non-null  float64
 1   title        15230 non-null  object
 2   category     15230 non-null  object
 3   address      15230 non-null  object
 4   tel          15230 non-null  object
 5   longitude    15230 non-null  float64
 6   latitude     15230 non-null  float64
 7   imgUrl       12353 non-null  object
 8   summary      9720 non-null   object
 9   naverDataId  15230 non-null  float64
dtypes: float64(4), object(6)
memory usage: 1.3+ MB

In [6]:
df1 = df1.astype({'id':'int', 'naverDataId':'int'})

In [7]:
df1 = df1.reset_index(drop=True)

In [8]:
df1

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId
0,2,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
1,3,섬고기,정육점,인천광역시 강화군 길상면 삼랑성길 4,010-3355-1796,126.491346,37.639160,https://search.pstatic.net/common/?autoRotate=...,1969년 시작된 섬고기는 \n청정지역 강화도에서 자란 질좋은 한우암소를 Wet A...,1051601274
2,4,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
3,5,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
4,6,한옥카페 궁,"카페,디저트",인천광역시 강화군 내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
...,...,...,...,...,...,...,...,...,...,...
15225,19994,띵호와중화요리,중식당,인천광역시 부평구 부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
15226,19995,라궁 마라탕꼬치,아시아음식,인천광역시 부평구 길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
15227,19997,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
15228,19999,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
15229,20000,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217

In [ ]:
# 식당관련 카테고리가 아닌 경우 제거

In [9]:
df1['category'].unique()

array(['생선회', '정육점', '장어,먹장어요리', '게요리', '카페,디저트', '족발,보쌈', '브런치', '해장국',
       '요리주점', '피자', '노래방', '칼국수,만두', '해물,생선요리', '매운탕,해물탕', '햄버거', '카페',
       '라이브카페', '모텔', '이탈리아음식', '치킨,닭강정', '양식', '오리요리', '한식', '관광농원,팜스테이',
       '순대,순댓국', '스파게티,파스타전문', '국수', '김밥', '채소재배', '곰탕,설렁탕', '전통공예',
       '찌개,전골', '중식당', '펜션', '정육식당', '백반,가정식', '생선구이', '장례식장', '한정식',
       '감자탕', '보리밥', '소고기', '두부요리', '육류,고기요리', '찐빵', '백숙,삼계탕', '떡,한과',
       '뷔페', '돼지고기구이', '곱창,막창,양', '장소대여', '아귀찜,해물찜', '포장마차', '베이커리',
       '추어탕', '굴요리', '닭갈비', '맥주,호프', '중개업', '초밥,롤', '분식', '사철,영양탕',
       '종합분식', '한방카페', '국밥', '쌈밥', '떡류제조', '양꼬치', '떡볶이', '체험마을', '돈가스',
       '젓갈', '찜닭', '향토음식', '패션잡화', '캠핑,야영장', '조개요리', '차', '편의점', '서점',
       '호떡', '일식당', '닭볶음탕', '닭요리', '애견카페', '도넛', '우동,소바', '치과', '만두',
       '퓨전음식', '죽', '카레', '막국수', '성곽명', '스페인음식', '패밀리레스토랑', '소고기구이', '냉면',
       '한식뷔페', '이북음식', '부속시설', '이자카야', '식료품제조', '콘도,리조트', '출장요리', '남성의류',
       '다방', '조경건설', '주꾸미요리', '관람,체험', '미용실', '도시락,컵밥', '민박', '드럭스토어',
       '사회복지단체', '반찬가게', '베트남음식', '인터넷상거래', '퍼블릭골프장', '수산물', '전,빈대떡',
       '공방', '테마카페', '당구장', '오뎅,꼬치', '갤러리,화랑', '프랑스음식', '연수기,정수기', '노인복지',
       '케이크전문', '꽃집,꽃배달', '반려견놀이터', '호텔', '수산물가공,제조', '낙지요리', '전복요리',
       '아시아음식', '야식', '수상스키', '민비아구찜해물찜', '낚시터', '종합도소매', '샤브샤브', '33떡볶이',
       '시장', '기념물', '바(BAR)', '여성의류', '테이크아웃커피', '공항라운지', '와인', '백화점',
       '헬스장', '고기원칙', '골프연습장', '일본식라면', '태국음식', '사진,스튜디오', '일식튀김,꼬치',
       '용달', '세차', '양갈비', '갤러리카페', '대게요리', '덮밥', '스테이크,립', '전통,민속주점',
       '인도음식', '단란주점', '영화관', '전문디자인', '샌드위치', '웨딩컨설팅,플래너', '화물운송', '토스트',
       '만화방', '학원', '비빔밥', '문어부인삼교비', '육류', '특수화물', '복어요리', '기사식당', '베이글',
       '블랙박스', '클럽', '복합문화공간', '다이어트,샐러드', '지하철,전철', '기타건축자재', '문구,팬시용품',
       '빙수', '섬', '라면', '수선', '유흥주점', '닭발', '핫도그', '이벤트,파티', '약국',
       '스크린골프장', '터키음식', '스터디카페', '킹크랩요리', '캠코더,카메라', '타이어,휠', '식료품',
       '오므라이스', '고기뷔페', '보드카페', '한지공예', '수족관', '키즈카페,실내놀이터', '과일',
       '과일,주스전문점', '달쫀', '농수산물', '한복대여', '와플', '조명장치제조', '전자담배', '크레페',
       '멕시코,남미음식', '게스트하우스', '어린이집', '유람선,관광선', '술집', '실내매장', '건어물',
       '건강기능식품제조', '갈비탕', '플라워카페', '일반휴게소', '공연장', '스포츠용품', '나무제품제조',
       '미술,공예품', '가구,인테리어', '직판장', '귀금속,시계', '금매매', '74떡뽀끼', '전동모빌리티',
       '딤섬,중식만두', '개성진찹쌀순대', '목욕탕,사우나', '마사지,지압', '쉐어하우스,하숙', '주먹밥',
       '보세의류', '복권,로또', '동물병원', '문화재', '바닷가재요리', '내과', '동물사료제조', '산부인과',
       '컨설팅', '화장품,향수', '스포츠시설', '호스팅,관련서비스업', '차,커피', '스크린야구장', '메이크업',
       '무한리필 마포서서갈비', '오징어요리', '한의원', '바람난탕수육', '속눈썹증모,연장', '박물관',
       '자동차정비,수리', '미용', '서오릉피자', '급식', '종합패션', '피부과', '도시,테마공원', '볼링장',
       '신복관', '예식장', '자동차용품,액세서리', '소아청소년과', '여성캐주얼', '슈퍼,마트', '필라테스',
       '불닭', '악기', '반려동물미용', '이비인후과', '목욕,찜질', '두부제조', '정형외과', '기업', '안과',
       '자전거', '전통문화', '장금수부대찌개', '장수통닭', '댄스학원', 'PC방', '페인트', '공연,연극시설',
       '댄스스포츠', '방앗간', '배관,냉난방공사', '장난감', '셀프세차', '안경원', '푸드트럭', '인테리어소품',
       '해양수산부', '교습학원,교습소', '운세,사주', '게임', '이사', '가공식품', '등산,아웃도어', '식품',
       '국제,항공화물', '101번지남산돈까스', '가정의학과', 'IT서비스', '주류', '피부,체형관리',
       '감성낙곱새', '거궁', '사격장', '전통숙소', '셀프,대여스튜디오', '심리상담', '캐주얼웨어', '달떡볶이',
       '전분제품,당류제조', '도서관', '컴퓨터', '인테리어디자인', '침구,커튼', '테니스장', '앤틱가구',
       '오락시설', '피아노', '밀키트', '미향해장국', '여객선', '떡카페', '네일아트,네일샵', '북카페',
       '초콜릿전문점', '찜질방', '다이어트식품', '그리스음식', '왁싱,제모', '침대', '신룽푸마라탕',
       '프랜차이즈본사', '수영용품', '아부찌부대찌개', '경영컨설팅', '전시,판매', '교복', '손세차', '무역',
       '독립서점', '과자,사탕,초코렛', '태권도', '폐백,이바지음식', '상가,아케이드', '영어학원', '음악학원',
       '오니기리', '일식,초밥뷔페', '무예,격투기', '해산물뷔페', '광고,마케팅', '주방용품', '호두과자',
       '푸드코트', '도시락,조리식품제조', '3일국밥', 'JVL부대찌개', '정신건강의학과', '인력공급,고용알선',
       '건강기능보조식품', '머리염색', '지원,대행', '스포츠센터', '건축자재,용품', '닭장수후라이드', '임대업',
       '장애인종합복지관', '전자,전기', '사주카페', '유아동복', '화장품제조', '미스터빠삭', '다이어트,비만',
       '패션', '바베큐와춤을', '악세사리제조', '채소', '종합사회복지관', '산,고개', '소파,내장가구제조',
       '금속가공제품제조', '장애인복지시설', '롤러,인라인스케이트장', '실내운전연습장', '우유,유제품', '잔잔',
       '슬라임카페', '휴대폰', '종합생활용품', '자쿠와', '베어링,기어,동력전달장치제조', '박람회,전시회',
       '절연선,케이블제조', '쉐보레서비스센터', '청소', '중국어학원', '오토바이수리', '방탈출카페', '드럼',
       '문화센터', '실내골프연습장', '아파트', '아동,청소년상담', '수도설비공사', '화덕고깃간', '룸카페',
       '결혼정보회사', '고레카레', '과실,채소가공,제조', '자연,생태공원', '컴퓨터,모니터', '플라스틱용기제조',
       '닭발싸롱', '곡물가공,제조'], dtype=object)

In [ ]:
# 버릴 카테고리

In [10]:
dummy = ['정육점','노래방','라이브카페','모텔','관광농원,팜스테이','채소재배','전통공예','펜션','장례식장','장소대여'
         '맥주,호프', '중개업','젓갈','패션잡화','캠핑,야영장','차','편의점', '서점','애견카페','치과','성곽명',
         '조경건설','관람,체험','미용실','민박','드럭스토어','사회복지단체','반찬가게','인터넷상거래', '퍼블릭골프장',
         '공방','당구장','갤러리,화랑','연수기,정수기','노인복지','꽃집,꽃배달','반려견놀이터','호텔','수산물가공,제조',
         '수상스키','민비아구찜해물찜','낚시터','종합도소매','33떡볶이','시장','기념물','바(BAR)','여성의류','테이크아웃커피',
         '공항라운지','와인','백화점','헬스장','고기원칙','골프연습장','사진,스튜디오','용달','세차','전통,민속주점',
         '단란주점','영화관','전문디자인''웨딩컨설팅,플래너','화물운송','만화방','학원','문어부인삼교비','특수화물','베이글',
         '블랙박스','클럽','복합문화공간','지하철,전철','기타건축자재','문구,팬시용품','섬','수선','유흥주점','이벤트,파티','약국',
         '스크린골프장','스터디카페','캠코더,카메라','타이어,휠','식료품','보드카페','한지공예','수족관','키즈카페,실내놀이터',
         '과일','달쫀','농수산물','한복대여','조명장치제조','전자담배','게스트하우스','어린이집','유람선,관광선','술집','실내매장',
         '건어물','건강기능식품제조','일반휴게소','공연장','스포츠용품','나무제품제조','미술,공예품','가구,인테리어','직판장',
         '귀금속,시계','금매매','74떡뽀끼','전동모빌리티','개성진찹쌀순대','목욕탕,사우나','마사지,지압','쉐어하우스,하숙',
         '보세의류','복권,로또','동물병원','문화재','내과','동물사료제조','산부인과','컨설팅','화장품,향수','스포츠시설', 
         '호스팅,관련서비스업','스크린야구장', '메이크업','무한리필 마포서서갈비','한의원','바람난탕수육','속눈썹증모,연장',
         '박물관','자동차정비,수리', '미용', '서오릉피자', '급식', '종합패션', '피부과', '도시,테마공원', '볼링장','신복관',
         '예식장', '자동차용품,액세서리', '소아청소년과', '여성캐주얼', '슈퍼,마트', '필라테스','악기', '반려동물미용',
         '이비인후과', '목욕,찜질', '두부제조', '정형외과', '기업', '안과','자전거', '전통문화', '장금수부대찌개', '장수통닭', 
         '댄스학원', 'PC방', '페인트', '공연,연극시설','댄스스포츠', '방앗간', '배관,냉난방공사', '장난감', '셀프세차', '안경원',
         '푸드트럭', '인테리어소품','해양수산부', '교습학원,교습소', '운세,사주', '게임', '이사', '가공식품', '등산,아웃도어', 
         '식품','국제,항공화물', '101번지남산돈까스', '가정의학과', 'IT서비스', '주류', '피부,체형관리','감성낙곱새', '거궁',
         '사격장', '전통숙소', '셀프,대여스튜디오', '심리상담', '캐주얼웨어', '달떡볶이','전분제품,당류제조', '도서관', '컴퓨터',
         '인테리어디자인', '침구,커튼', '테니스장', '앤틱가구','오락시설', '피아노', '밀키트', '미향해장국', '여객선',
         '네일아트,네일샵','찜질방', '다이어트식품','왁싱,제모', '침대', '신룽푸마라탕','프랜차이즈본사', '수영용품', 
         '아부찌부대찌개', '경영컨설팅', '전시,판매', '교복', '손세차', '무역','무예,격투기','광고,마케팅', '주방용품',
         '푸드코트', '도시락,조리식품제조', '3일국밥', 'JVL부대찌개', '정신건강의학과', '인력공급,고용알선','건강기능보조식품',
         '머리염색', '지원,대행', '스포츠센터', '건축자재,용품', '닭장수후라이드', '임대업','장애인종합복지관', '전자,전기',
         '사주카페', '유아동복', '화장품제조', '미스터빠삭', '다이어트,비만','패션', '바베큐와춤을', '악세사리제조', '채소',
         '종합사회복지관', '산,고개', '소파,내장가구제조','금속가공제품제조', '장애인복지시설', '롤러,인라인스케이트장',
         '실내운전연습장', '우유,유제품', '잔잔','슬라임카페', '휴대폰', '종합생활용품', '자쿠와', '베어링,기어,동력전달장치제조',
         '박람회,전시회','절연선,케이블제조', '쉐보레서비스센터', '청소', '중국어학원', '오토바이수리', '방탈출카페', '드럼',
         '문화센터', '실내골프연습장', '아파트', '아동,청소년상담', '수도설비공사', '화덕고깃간', '룸카페','결혼정보회사', 
         '고레카레', '과실,채소가공,제조', '자연,생태공원', '컴퓨터,모니터', '플라스틱용기제조','닭발싸롱', '곡물가공,제조',
         '체험마을', '떡류제조', '맥주,호프', '부속시설','식료품제조', '콘도,리조트', '출장요리', '남성의류','전문디자인',
         '웨딩컨설팅,플래너','독립서점','과자,사탕,초코렛', '태권도', '폐백,이바지음식', '상가,아케이드', '영어학원', '음악학원']

In [11]:
df1['category'].isin(dummy)

0        False
1         True
2        False
3        False
4        False
         ...
15225    False
15226    False
15227    False
15228    False
15229    False
Name: category, Length: 15230, dtype: bool

In [12]:
df1[df1['category'].isin(dummy)].index

Int64Index([    1,    11,    19,    21,    47,    65,    73,    77,    89,
              113,
            ...
            15025, 15031, 15037, 15059, 15098, 15117, 15125, 15152, 15161,
            15176],
           dtype='int64', length=1501)

In [13]:
df1 = df1.drop(df1[df1['category'].isin(dummy)].index, axis=0)

In [14]:
df1

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId
0,2,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
2,4,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
3,5,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
4,6,한옥카페 궁,"카페,디저트",인천광역시 강화군 내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
5,8,1박2일 족발,"족발,보쌈",인천광역시 강화군 강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754
...,...,...,...,...,...,...,...,...,...,...
15225,19994,띵호와중화요리,중식당,인천광역시 부평구 부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
15226,19995,라궁 마라탕꼬치,아시아음식,인천광역시 부평구 길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
15227,19997,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
15228,19999,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
15229,20000,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13729 entries, 0 to 15229
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           13729 non-null  int32
 1   title        13729 non-null  object
 2   category     13729 non-null  object
 3   address      13729 non-null  object
 4   tel          13729 non-null  object
 5   longitude    13729 non-null  float64
 6   latitude     13729 non-null  float64
 7   imgUrl       11160 non-null  object
 8   summary      8647 non-null   object
 9   naverDataId  13729 non-null  int32
dtypes: float64(2), int32(2), object(6)
memory usage: 1.0+ MB

In [16]:
df1['category'].unique()

array(['생선회', '장어,먹장어요리', '게요리', '카페,디저트', '족발,보쌈', '브런치', '해장국', '요리주점',
       '피자', '칼국수,만두', '해물,생선요리', '매운탕,해물탕', '햄버거', '카페', '이탈리아음식',
       '치킨,닭강정', '양식', '오리요리', '한식', '순대,순댓국', '스파게티,파스타전문', '국수', '김밥',
       '곰탕,설렁탕', '찌개,전골', '중식당', '정육식당', '백반,가정식', '생선구이', '한정식', '감자탕',
       '보리밥', '소고기', '두부요리', '육류,고기요리', '찐빵', '백숙,삼계탕', '떡,한과', '뷔페',
       '돼지고기구이', '곱창,막창,양', '장소대여', '아귀찜,해물찜', '포장마차', '베이커리', '추어탕',
       '굴요리', '닭갈비', '초밥,롤', '분식', '사철,영양탕', '종합분식', '한방카페', '국밥', '쌈밥',
       '양꼬치', '떡볶이', '돈가스', '찜닭', '향토음식', '조개요리', '호떡', '일식당', '닭볶음탕',
       '닭요리', '도넛', '우동,소바', '만두', '퓨전음식', '죽', '카레', '막국수', '스페인음식',
       '패밀리레스토랑', '소고기구이', '냉면', '한식뷔페', '이북음식', '이자카야', '다방', '주꾸미요리',
       '도시락,컵밥', '베트남음식', '수산물', '전,빈대떡', '테마카페', '오뎅,꼬치', '프랑스음식',
       '케이크전문', '낙지요리', '전복요리', '아시아음식', '야식', '샤브샤브', '일본식라면', '태국음식',
       '일식튀김,꼬치', '양갈비', '갤러리카페', '대게요리', '덮밥', '스테이크,립', '인도음식', '샌드위치',
       '토스트', '비빔밥', '육류', '복어요리', '기사식당', '다이어트,샐러드', '빙수', '라면', '닭발',
       '핫도그', '터키음식', '킹크랩요리', '오므라이스', '고기뷔페', '과일,주스전문점', '와플', '크레페',
       '멕시코,남미음식', '갈비탕', '플라워카페', '딤섬,중식만두', '주먹밥', '바닷가재요리', '차,커피',
       '오징어요리', '불닭', '떡카페', '북카페', '초콜릿전문점', '그리스음식', '오니기리', '일식,초밥뷔페',
       '해산물뷔페', '호두과자'], dtype=object)

In [17]:
df1 = df1.drop(df1[df1['category'] == '장소대여'].index, axis=0)

In [18]:
df1 = df1.drop(df1[df1['category'] == '맥주,호프'].index, axis=0)

In [19]:
df1 = df1.drop(df1[df1['category'] == '과자,사탕,초코렛'].index, axis=0)

In [20]:
df1

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId
0,2,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
2,4,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
3,5,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
4,6,한옥카페 궁,"카페,디저트",인천광역시 강화군 내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
5,8,1박2일 족발,"족발,보쌈",인천광역시 강화군 강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754
...,...,...,...,...,...,...,...,...,...,...
15225,19994,띵호와중화요리,중식당,인천광역시 부평구 부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
15226,19995,라궁 마라탕꼬치,아시아음식,인천광역시 부평구 길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
15227,19997,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
15228,19999,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
15229,20000,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217

In [ ]:
# 주소를 시, 군, 상세주소 컬럼으로 분리

In [ ]:
# 1. 시 분리

In [21]:
df1['address'].str.split(' ').str[0]

0        인천광역시
2        인천광역시
3        인천광역시
4        인천광역시
5        인천광역시
         ...
15225    인천광역시
15226    인천광역시
15227    인천광역시
15228    인천광역시
15229    인천광역시
Name: address, Length: 13716, dtype: object

In [22]:
df1['locCity'] = df1['address'].str.split(' ').str[0]

In [23]:
df1

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId,locCity
0,2,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600,인천광역시
2,4,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969,인천광역시
3,5,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985,인천광역시
4,6,한옥카페 궁,"카페,디저트",인천광역시 강화군 내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161,인천광역시
5,8,1박2일 족발,"족발,보쌈",인천광역시 강화군 강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754,인천광역시
...,...,...,...,...,...,...,...,...,...,...,...
15225,19994,띵호와중화요리,중식당,인천광역시 부평구 부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056,인천광역시
15226,19995,라궁 마라탕꼬치,아시아음식,인천광역시 부평구 길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004,인천광역시
15227,19997,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195,인천광역시
15228,19999,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571,인천광역시
15229,20000,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217,인천광역시

In [24]:
df1['locCity'].unique()

array(['인천광역시', '경기도', '충청남도'], dtype=object)

In [25]:
df1[df1['locCity'] != '인천광역시'].index

Int64Index([   12,   632,  1239,  1252, 10419, 10541, 10861, 10871, 11046,
            11104, 11154, 11933, 12053, 12443, 12647, 14828, 14938, 14958],
           dtype='int64')

In [26]:
df1 = df1.drop(df1[df1['locCity'] != '인천광역시'].index, axis=0)

In [27]:
df1['locCity'].unique()

array(['인천광역시'], dtype=object)

In [ ]:
# 2. 구 분리

In [28]:
df1['address'].str.split(' ').str[1]

0        강화군
2        강화군
3        강화군
4        강화군
5        강화군
        ...
15225    부평구
15226    부평구
15227    부평구
15228    부평구
15229    부평구
Name: address, Length: 13698, dtype: object

In [29]:
df1['address'].str.split(' ').str[1].unique()

array(['강화군', '옹진군', '중구', '서구', '미추홀구', '연수구', '동구', '남동구', '부평구'],
      dtype=object)

In [30]:
df1['locDistrict'] = df1['address'].str.split(' ').str[1]

In [31]:
df1

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId,locCity,locDistrict
0,2,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600,인천광역시,강화군
2,4,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969,인천광역시,강화군
3,5,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985,인천광역시,강화군
4,6,한옥카페 궁,"카페,디저트",인천광역시 강화군 내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161,인천광역시,강화군
5,8,1박2일 족발,"족발,보쌈",인천광역시 강화군 강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754,인천광역시,강화군
...,...,...,...,...,...,...,...,...,...,...,...,...
15225,19994,띵호와중화요리,중식당,인천광역시 부평구 부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056,인천광역시,부평구
15226,19995,라궁 마라탕꼬치,아시아음식,인천광역시 부평구 길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004,인천광역시,부평구
15227,19997,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195,인천광역시,부평구
15228,19999,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571,인천광역시,부평구
15229,20000,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217,인천광역시,부평구

In [ ]:
# 3. 상세주소 분리

In [32]:
(df1['address'].str.split(' ').str[2:])

0              [길상면, 해안남로619번길, 21]
2                  [길상면, 해안남로, 298]
3                  [내가면, 중앙로, 1200]
4              [내가면, 중앙로1128번길, 21]
5                    [강화읍, 북문길, 12]
                    ...
15225                     [부영로, 26]
15226             [길주남로, 115-1, 1층]
15227    [경원대로1403번길, 33, 신세계음향프라자]
15228                [길주로647번길, 17]
15229                   [광장로4번길, 8]
Name: address, Length: 13698, dtype: object

In [33]:
def get_address(array):
    string = ''
    for i in array:
        string = string + ' ' + i
    string = string.strip()
    return string

In [34]:
get_address(df1['address'].str.split(' ').str[2:][0])

'길상면 해안남로619번길 21'

In [35]:
df1['address'].str.split(' ').str[2:].apply(get_address)

0              길상면 해안남로619번길 21
2                  길상면 해안남로 298
3                  내가면 중앙로 1200
4              내가면 중앙로1128번길 21
5                    강화읍 북문길 12
                  ...
15225                    부영로 26
15226             길주남로 115-1 1층
15227    경원대로1403번길 33 신세계음향프라자
15228               길주로647번길 17
15229                  광장로4번길 8
Name: address, Length: 13698, dtype: object

In [36]:
df1['locDetail'] = df1['address'].str.split(' ').str[2:].apply(get_address)

In [37]:
df1

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId,locCity,locDistrict,locDetail
0,2,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600,인천광역시,강화군,길상면 해안남로619번길 21
2,4,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969,인천광역시,강화군,길상면 해안남로 298
3,5,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985,인천광역시,강화군,내가면 중앙로 1200
4,6,한옥카페 궁,"카페,디저트",인천광역시 강화군 내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161,인천광역시,강화군,내가면 중앙로1128번길 21
5,8,1박2일 족발,"족발,보쌈",인천광역시 강화군 강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754,인천광역시,강화군,강화읍 북문길 12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15225,19994,띵호와중화요리,중식당,인천광역시 부평구 부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056,인천광역시,부평구,부영로 26
15226,19995,라궁 마라탕꼬치,아시아음식,인천광역시 부평구 길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004,인천광역시,부평구,길주남로 115-1 1층
15227,19997,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195,인천광역시,부평구,경원대로1403번길 33 신세계음향프라자
15228,19999,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571,인천광역시,부평구,길주로647번길 17
15229,20000,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217,인천광역시,부평구,광장로4번길 8

In [ ]:
# 중복행 제거

In [38]:
df1.drop_duplicates(subset=['title','address'], keep='first', inplace=False, ignore_index=False)

,id,title,category,address,tel,longitude,latitude,imgUrl,summary,naverDataId,locCity,locDistrict,locDetail
0,2,보광호,생선회,인천광역시 강화군 길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600,인천광역시,강화군,길상면 해안남로619번길 21
2,4,장어마을,"장어,먹장어요리",인천광역시 강화군 길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969,인천광역시,강화군,길상면 해안남로 298
3,5,충남서산집,게요리,인천광역시 강화군 내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985,인천광역시,강화군,내가면 중앙로 1200
4,6,한옥카페 궁,"카페,디저트",인천광역시 강화군 내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161,인천광역시,강화군,내가면 중앙로1128번길 21
5,8,1박2일 족발,"족발,보쌈",인천광역시 강화군 강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754,인천광역시,강화군,강화읍 북문길 12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15225,19994,띵호와중화요리,중식당,인천광역시 부평구 부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056,인천광역시,부평구,부영로 26
15226,19995,라궁 마라탕꼬치,아시아음식,인천광역시 부평구 길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004,인천광역시,부평구,길주남로 115-1 1층
15227,19997,라덴,요리주점,인천광역시 부평구 경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195,인천광역시,부평구,경원대로1403번길 33 신세계음향프라자
15228,19999,라무진 굴포천역점,양갈비,인천광역시 부평구 길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571,인천광역시,부평구,길주로647번길 17
15229,20000,534라비아,양식,인천광역시 부평구 광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217,인천광역시,부평구,광장로4번길 8

In [39]:
df1 = df1.drop_duplicates(subset=['title','address'], keep='first', inplace=False, ignore_index=False)

In [40]:
df1 = df1.reset_index(drop=True)

In [ ]:
# 기존 주소 drop

In [41]:
df1 = df1.drop('address', axis=1)

In [42]:
df1.columns

Index(['id', 'title', 'category', 'tel', 'longitude', 'latitude', 'imgUrl',
       'summary', 'naverDataId', 'locCity', 'locDistrict', 'locDetail'],
      dtype='object')

In [ ]:
# 테이블설계와 같게 컬럼순서 변경

In [43]:
df1 = df1[ ['id', 'title', 'category', 'locCity', 'locDistrict', 'locDetail', 'tel', 'longitude', 'latitude', 'imgUrl', 'summary', 'naverDataId'] ]

In [44]:
df1

,id,title,category,locCity,locDistrict,locDetail,tel,longitude,latitude,imgUrl,summary,naverDataId
0,2,보광호,생선회,인천광역시,강화군,길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
1,4,장어마을,"장어,먹장어요리",인천광역시,강화군,길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
2,5,충남서산집,게요리,인천광역시,강화군,내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
3,6,한옥카페 궁,"카페,디저트",인천광역시,강화군,내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
4,8,1박2일 족발,"족발,보쌈",인천광역시,강화군,강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754
...,...,...,...,...,...,...,...,...,...,...,...,...
12123,19994,띵호와중화요리,중식당,인천광역시,부평구,부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
12124,19995,라궁 마라탕꼬치,아시아음식,인천광역시,부평구,길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
12125,19997,라덴,요리주점,인천광역시,부평구,경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
12126,19999,라무진 굴포천역점,양갈비,인천광역시,부평구,길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
12127,20000,534라비아,양식,인천광역시,부평구,광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217

In [ ]:
# 파일로 저장

In [51]:
df1.to_csv('RESTAURANT.csv')

In [52]:
pd.read_csv('RESTAURANT.csv', index_col=0)

,id,title,category,locCity,locDistrict,locDetail,tel,longitude,latitude,imgUrl,summary,naverDataId
0,2,보광호,생선회,인천광역시,강화군,길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
1,4,장어마을,"장어,먹장어요리",인천광역시,강화군,길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
2,5,충남서산집,게요리,인천광역시,강화군,내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
3,6,한옥카페 궁,"카페,디저트",인천광역시,강화군,내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
4,8,1박2일 족발,"족발,보쌈",인천광역시,강화군,강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754
...,...,...,...,...,...,...,...,...,...,...,...,...
12123,19994,띵호와중화요리,중식당,인천광역시,부평구,부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
12124,19995,라궁 마라탕꼬치,아시아음식,인천광역시,부평구,길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
12125,19997,라덴,요리주점,인천광역시,부평구,경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
12126,19999,라무진 굴포천역점,양갈비,인천광역시,부평구,길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
12127,20000,534라비아,양식,인천광역시,부평구,광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217

In [ ]:
# 메뉴 데이터 전처리

In [48]:
df2 = pd.read_csv('DF_menu.csv', index_col=0)

In [49]:
df2

,id,restaurantId,menuName,price,introduction,menuImgUrl
0,1,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,2,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
2,3,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
3,4,2,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
4,5,2,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
...,...,...,...,...,...,...
71266,127836,20000,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
71267,127837,20000,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
71268,127838,20000,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
71269,127839,20000,커피(아메리카노),"3,500원",NaN,NaN
71270,127840,20000,홍차(마리아주프레르),"4,000원",NaN,NaN

In [ ]:
# 인덱스 초기화

In [51]:
df2 = df2.reset_index(drop=True)

In [54]:
df2

,id,restaurantId,menuName,price,introduction,menuImgUrl
0,1,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,2,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
2,3,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
3,4,2,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
4,5,2,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
...,...,...,...,...,...,...
127835,127836,20000,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
127836,127837,20000,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
127837,127838,20000,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
127838,127839,20000,커피(아메리카노),"3,500원",NaN,NaN
127839,127840,20000,홍차(마리아주프레르),"4,000원",NaN,NaN

In [53]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127840 entries, 0 to 127839
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            127840 non-null  int64
 1   restaurantId  127840 non-null  int64
 2   menuName      127838 non-null  object
 3   price         127838 non-null  object
 4   introduction  50628 non-null   object
 5   menuImgUrl    70959 non-null   object
dtypes: int64(2), object(4)
memory usage: 5.9+ MB

In [ ]:
# 결측치 제거

In [58]:
df2 = df2.dropna(subset=['menuName', 'price'])

In [59]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 127838 entries, 0 to 127839
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            127838 non-null  int64
 1   restaurantId  127838 non-null  int64
 2   menuName      127838 non-null  object
 3   price         127838 non-null  object
 4   introduction  50628 non-null   object
 5   menuImgUrl    70959 non-null   object
dtypes: int64(2), object(4)
memory usage: 6.8+ MB

In [60]:
df1['id'].unique()

array([    2,     4,     5, ..., 19997, 19999, 20000])

In [61]:
df2['restaurantId'].unique()

array([    2,     3,     4, ..., 19995, 19999, 20000], dtype=int64)

In [ ]:
# 식당 df에서 드랍된 식당의 메뉴제거

In [62]:
df2 = df2[df2['restaurantId'].isin(df1['id'])]

In [63]:
df2

,id,restaurantId,menuName,price,introduction,menuImgUrl
0,1,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,2,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
2,3,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
3,4,2,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
4,5,2,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
...,...,...,...,...,...,...
127835,127836,20000,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
127836,127837,20000,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
127837,127838,20000,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
127838,127839,20000,커피(아메리카노),"3,500원",NaN,NaN
127839,127840,20000,홍차(마리아주프레르),"4,000원",NaN,NaN

In [ ]:
# 중복행 제거

In [64]:
df2 = df2.drop_duplicates(subset=['restaurantId','menuName', 'price'], keep='first', inplace=False, ignore_index=False)

In [65]:
df2 = df2.reset_index(drop=True)

In [66]:
df2

,id,restaurantId,menuName,price,introduction,menuImgUrl
0,1,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,4,2,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
2,5,2,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
3,6,2,우럭,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_115/164...
4,7,2,도미,"50,000원",NaN,NaN
...,...,...,...,...,...,...
101288,127836,20000,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101289,127837,20000,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101290,127838,20000,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101291,127839,20000,커피(아메리카노),"3,500원",NaN,NaN
101292,127840,20000,홍차(마리아주프레르),"4,000원",NaN,NaN

In [67]:
df1

,id,title,category,locCity,locDistrict,locDetail,tel,longitude,latitude,imgUrl,summary,naverDataId
0,2,보광호,생선회,인천광역시,강화군,길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
1,4,장어마을,"장어,먹장어요리",인천광역시,강화군,길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
2,5,충남서산집,게요리,인천광역시,강화군,내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
3,6,한옥카페 궁,"카페,디저트",인천광역시,강화군,내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
4,8,1박2일 족발,"족발,보쌈",인천광역시,강화군,강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754
...,...,...,...,...,...,...,...,...,...,...,...,...
12123,19994,띵호와중화요리,중식당,인천광역시,부평구,부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
12124,19995,라궁 마라탕꼬치,아시아음식,인천광역시,부평구,길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
12125,19997,라덴,요리주점,인천광역시,부평구,경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
12126,19999,라무진 굴포천역점,양갈비,인천광역시,부평구,길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
12127,20000,534라비아,양식,인천광역시,부평구,광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217

In [128]:
# 식당df의 id를 초기화한다.
# 메뉴df에서 초기화하기 전의 식당id를 참조하고 있으므로 아직 이전 id는 삭제하지 않는다

In [68]:
df1 = df1.reset_index().rename(columns={'index': 'new_id'})

In [69]:
df1['new_id'] = df1['new_id'] + 1

In [70]:
df1 = df1.rename(columns={'new_id':'id', 'id':'old_id', 'title':'name'})

In [71]:
df1

,id,old_id,name,category,locCity,locDistrict,locDetail,tel,longitude,latitude,imgUrl,summary,naverDataId
0,1,2,보광호,생선회,인천광역시,강화군,길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
1,2,4,장어마을,"장어,먹장어요리",인천광역시,강화군,길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
2,3,5,충남서산집,게요리,인천광역시,강화군,내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
3,4,6,한옥카페 궁,"카페,디저트",인천광역시,강화군,내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
4,5,8,1박2일 족발,"족발,보쌈",인천광역시,강화군,강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12123,12124,19994,띵호와중화요리,중식당,인천광역시,부평구,부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
12124,12125,19995,라궁 마라탕꼬치,아시아음식,인천광역시,부평구,길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
12125,12126,19997,라덴,요리주점,인천광역시,부평구,경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
12126,12127,19999,라무진 굴포천역점,양갈비,인천광역시,부평구,길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
12127,12128,20000,534라비아,양식,인천광역시,부평구,광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217

In [ ]:
# 파일로 저장

In [70]:
df1.to_csv('RESTAURANT.csv')

In [72]:
df2

,id,restaurantId,menuName,price,introduction,menuImgUrl
0,1,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,4,2,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
2,5,2,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
3,6,2,우럭,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_115/164...
4,7,2,도미,"50,000원",NaN,NaN
...,...,...,...,...,...,...
101288,127836,20000,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101289,127837,20000,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101290,127838,20000,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101291,127839,20000,커피(아메리카노),"3,500원",NaN,NaN
101292,127840,20000,홍차(마리아주프레르),"4,000원",NaN,NaN

In [ ]:
# 식당df의 식당id가 바뀌었으므로 메뉴df의 restaurantId도 그에 맞게 바꿔줘야 한다.
# 식당df의 id와 old_id를 merge한다.

In [73]:
df2 = df2.merge(df1[['id', 'old_id']], left_on='restaurantId', right_on='old_id')

In [74]:
df2

,id_x,restaurantId,menuName,price,introduction,menuImgUrl,id_y,old_id
0,1,2,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...,1,2
1,4,2,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...,1,2
2,5,2,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...,1,2
3,6,2,우럭,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_115/164...,1,2
4,7,2,도미,"50,000원",NaN,NaN,1,2
...,...,...,...,...,...,...,...,...
101288,127836,20000,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101289,127837,20000,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101290,127838,20000,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101291,127839,20000,커피(아메리카노),"3,500원",NaN,NaN,12128,20000
101292,127840,20000,홍차(마리아주프레르),"4,000원",NaN,NaN,12128,20000

In [ ]:
# restaurantId를 갱신된 식당id로 바꿔준다

In [75]:
df2 = df2.drop(columns=['id_x', 'restaurantId']).rename(columns={'id_y': 'restaurantId', 'old_id':'old_restaurantId'})

In [76]:
df2

,menuName,price,introduction,menuImgUrl,restaurantId,old_restaurantId
0,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...,1,2
1,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...,1,2
2,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...,1,2
3,우럭,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_115/164...,1,2
4,도미,"50,000원",NaN,NaN,1,2
...,...,...,...,...,...,...
101288,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101289,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101290,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101291,커피(아메리카노),"3,500원",NaN,NaN,12128,20000
101292,홍차(마리아주프레르),"4,000원",NaN,NaN,12128,20000

In [ ]:
# 메뉴id 초기화

In [77]:
df2 = df2.reset_index().rename(columns={'index':'id'})

In [78]:
df2['id'] = df2['id']+1

In [79]:
df2

,id,menuName,price,introduction,menuImgUrl,restaurantId,old_restaurantId
0,1,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...,1,2
1,2,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...,1,2
2,3,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...,1,2
3,4,우럭,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_115/164...,1,2
4,5,도미,"50,000원",NaN,NaN,1,2
...,...,...,...,...,...,...,...
101288,101289,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101289,101290,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101290,101291,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...,12128,20000
101291,101292,커피(아메리카노),"3,500원",NaN,NaN,12128,20000
101292,101293,홍차(마리아주프레르),"4,000원",NaN,NaN,12128,20000

In [ ]:
# 테이블 설계와 같게 컬럼명 변경

In [80]:
df2 = df2.rename(columns={'introduction':'description', 'menuImgUrl':'imgUrl'})

In [ ]:
# 테이블 설계와 같게 컬럼순서 변경

In [81]:
df2 = df2[ ['id', 'old_restaurantId', 'restaurantId', 'menuName', 'price', 'description', 'imgUrl'] ]

In [82]:
df2

,id,old_restaurantId,restaurantId,menuName,price,description,imgUrl
0,1,2,1,A세트인기대표,"59,000원",해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,2,2,1,숭어,"25,000원",NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
2,3,2,1,광어,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
3,4,2,1,우럭,"40,000원",NaN,https://ldb-phinf.pstatic.net/20220207_115/164...
4,5,2,1,도미,"50,000원",NaN,NaN
...,...,...,...,...,...,...,...
101288,101289,20000,12128,시금치플렛브래드,"18,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101289,101290,20000,12128,불고기크림파스타,"15,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101290,101291,20000,12128,살치살스테이크,"34,000원",NaN,https://search.pstatic.net/common/?autoRotate=...
101291,101292,20000,12128,커피(아메리카노),"3,500원",NaN,NaN
101292,101293,20000,12128,홍차(마리아주프레르),"4,000원",NaN,NaN

In [110]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101293 entries, 0 to 101292
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                101293 non-null  int64
 1   old_restaurantId  101293 non-null  int32
 2   restaurantId      101293 non-null  int64
 3   menuName          101293 non-null  object
 4   price             101293 non-null  object
 5   description       39858 non-null   object
 6   imgUrl            55632 non-null   object
dtypes: int32(1), int64(2), object(4)
memory usage: 5.0+ MB

In [ ]:
# 가격이 변동인 데이터 처리

In [114]:
df2.loc[df2['price'] =='변동', 'price'] = 0

In [ ]:
# 가격에 ~가 포함된 데이터 처리

In [100]:
df2.loc[df2['price'].str.contains('~'), 'price'] = 0

In [115]:
(df2['price']==0).value_counts()

False    97273
True      4020
Name: price, dtype: int64

In [ ]:
# 불필요한 문자열 처리

In [117]:
df2['price'] = df2['price'].str.replace(',', '').str.replace('원','')

In [118]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101293 entries, 0 to 101292
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                101293 non-null  int64
 1   old_restaurantId  101293 non-null  int32
 2   restaurantId      101293 non-null  int64
 3   menuName          101293 non-null  object
 4   price             97273 non-null   object
 5   description       39858 non-null   object
 6   imgUrl            55632 non-null   object
dtypes: int32(1), int64(2), object(4)
memory usage: 5.0+ MB

In [120]:
df2['price'].isna().sum()

4020

In [129]:
df2

,id,old_restaurantId,restaurantId,menuName,price,description,imgUrl
0,1,2,1,A세트인기대표,59000,해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,2,2,1,숭어,25000,NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
2,3,2,1,광어,40000,NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
3,4,2,1,우럭,40000,NaN,https://ldb-phinf.pstatic.net/20220207_115/164...
4,5,2,1,도미,50000,NaN,NaN
...,...,...,...,...,...,...,...
101288,101289,20000,12128,시금치플렛브래드,18000,NaN,https://search.pstatic.net/common/?autoRotate=...
101289,101290,20000,12128,불고기크림파스타,15000,NaN,https://search.pstatic.net/common/?autoRotate=...
101290,101291,20000,12128,살치살스테이크,34000,NaN,https://search.pstatic.net/common/?autoRotate=...
101291,101292,20000,12128,커피(아메리카노),3500,NaN,NaN
101292,101293,20000,12128,홍차(마리아주프레르),4000,NaN,NaN

In [ ]:
# 파일로 저장

In [124]:
df2.to_csv('MENU.csv')

In [126]:
pd.read_csv('MENU.csv', index_col=0)

,id,old_restaurantId,restaurantId,menuName,price,description,imgUrl
0,1,2,1,A세트인기대표,59000,해산물모듬+제철모듬회+매운탕(지리탕),https://ldb-phinf.pstatic.net/20220203_236/164...
1,2,2,1,숭어,25000,NaN,https://ldb-phinf.pstatic.net/20220207_135/164...
2,3,2,1,광어,40000,NaN,https://ldb-phinf.pstatic.net/20220207_188/164...
3,4,2,1,우럭,40000,NaN,https://ldb-phinf.pstatic.net/20220207_115/164...
4,5,2,1,도미,50000,NaN,NaN
...,...,...,...,...,...,...,...
101288,101289,20000,12128,시금치플렛브래드,18000,NaN,https://search.pstatic.net/common/?autoRotate=...
101289,101290,20000,12128,불고기크림파스타,15000,NaN,https://search.pstatic.net/common/?autoRotate=...
101290,101291,20000,12128,살치살스테이크,34000,NaN,https://search.pstatic.net/common/?autoRotate=...
101291,101292,20000,12128,커피(아메리카노),3500,NaN,NaN
101292,101293,20000,12128,홍차(마리아주프레르),4000,NaN,NaN

In [127]:
pd.read_csv('RESTAURANT.csv', index_col=0)

,id,old_id,name,category,locCity,locDistrict,locDetail,tel,longitude,latitude,imgUrl,summary,naverDataId
0,1,2,보광호,생선회,인천광역시,강화군,길상면 해안남로619번길 21,032-937-7111,126.496185,37.598379,https://search.pstatic.net/common/?autoRotate=...,오션뷰 맛집 보광호.\n강화도에서 3대째 횟감을 직접 잡아 판매하는 어부 직영 횟집...,16561600
1,2,4,장어마을,"장어,먹장어요리",인천광역시,강화군,길상면 해안남로 298,032-937-0592,126.520175,37.610090,https://search.pstatic.net/common/?autoRotate=...,장어마을은 2001년 오픈하여 22년간 대대로 내려온 강화도 장어 맛집입니다.\n\...,11861969
2,3,5,충남서산집,게요리,인천광역시,강화군,내가면 중앙로 1200,032-933-8403,126.390996,37.704689,https://search.pstatic.net/common/?autoRotate=...,NaN,37239985
3,4,6,한옥카페 궁,"카페,디저트",인천광역시,강화군,내가면 중앙로1128번길 21,032-932-9321,126.397552,37.704103,https://search.pstatic.net/common/?autoRotate=...,"바다, 섬 그리고 산을 함께 즐길 수 있는 한옥카페, 수제 호박식혜 & 대추차가 맛...",38345161
4,5,8,1박2일 족발,"족발,보쌈",인천광역시,강화군,강화읍 북문길 12,032-933-0033,126.484899,37.748103,NaN,NaN,1251546754
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12123,12124,19994,띵호와중화요리,중식당,인천광역시,부평구,부영로 26,032-525-2500,126.717593,37.487541,https://search.pstatic.net/common/?autoRotate=...,기본에 충실한 띵호와중화요리\n착한가격 띵호와만의 특별한 맛과 푸짐한 양\n사장님이...,1066293056
12124,12125,19995,라궁 마라탕꼬치,아시아음식,인천광역시,부평구,길주남로 115-1 1층,032-504-8260,126.734682,37.504143,https://search.pstatic.net/common/?autoRotate=...,안녕하세요 ! 라궁마라탕&꼬치 입니다 !\n\n<< 라궁마라탕&꼬치 는요~ >>\n...,1665885004
12125,12126,19997,라덴,요리주점,인천광역시,부평구,경원대로1403번길 33 신세계음향프라자,070-7379-2233,126.725692,37.492787,NaN,NaN,31316195
12126,12127,19999,라무진 굴포천역점,양갈비,인천광역시,부평구,길주로647번길 17,032-505-5722,126.734270,37.507952,https://search.pstatic.net/common/?autoRotate=...,예약은 6시까지 가능합니다 22시30분에 주방 마감 이오니 참고 부탁드립니다.,1577548571
12127,12128,20000,534라비아,양식,인천광역시,부평구,광장로4번길 8,032-529-2756,126.722279,37.490808,https://search.pstatic.net/common/?autoRotate=...,100% 예약제로 손님들께 최고의 분위기와 음식을 정성을 다하는 '534라비아' 입...,1050960217